services:
  server:
    build: ./server
    ports:
      - 5050:5000
    command: npm start
    volumes:
      - ./server/src/:/app//server/src/
  client:
    build: ./client
    ports:
      - 8080:3000
    command: npm start
    volumes:
      - ./client/src/:/app/client/src/
  mongodb:
    image: mongo
    volumes:
      - ./server/src/:/app/src/
